== A Short Account of Barbara Blaugdone

In my youth and tender years I feared the Lord, and was afraid to offend him,
and was zealous and diligent in the profession I was in, and sought the Lord earnestly,
although I knew not where to find him,
until I was directed by Friends that came from the north (in 1654),
John Audland and John Camm by name,^
footnote:[See "`A Testimony to the glorious morning
of the day of visitation of the love of God,
and to the great and mighty power of the Lord,
which appeared in and with his two precious servants John Camm and John Audland,
who came to that city in the year 1654,`" in the
fourth chapter of Charles Marhsall`'s journal, www.friendslibrary.com.]
whose behaviour and deportment was such that it preached
before ever they opened their mouths;
and it was then revealed to me that they had the
everlasting gospel to preach in this city.
When they did open their mouths I was made to bless God
that I had lived to hear the everlasting gospel preached;
and they directed my mind unto the light of Christ, therein to wait,
which I was diligent to do, and found the virtue of it;
and as the evil was made manifest I departed from it, and willingly took up the cross,
and yielded obedience unto it in plainness of speech and apparel;
and the people were so offended with it when I went
into their public places and steeple-houses to speak,
that they took away their children from me, so that I lost almost all my employment;
and they kept me in prison a quarter of a year at a time.
Great were my sufferings in that day,
but the Lord so filled me with his power that I was preserved through it all;
and the diligent and faithful prospered then, and so they do now.

Therefore my council to Friends is, that they keep in God`'s power;
for there is no other way to be preserved nor to receive
life and salvation--it is my testimony for God;
for whoever shuns the cross and goes out of the power,
they lose their way and dishonour God;
but whoever keep in the faith and abide in the power, they are in safety.
I have had living experience of it,
and it has been with me a long while to publish it
for the benefit of those that are passing through,
and are yet to pass through sufferings, and therefore do I declare my experience.

And so, dear Friends, the cross is the way to the crown of life and glory;
and they that continue faithful and obedient, they obtain the eternal crown,
which they that are disobedient lose.
I speak my experience of the dealings of the Lord with me
in my travels and passings through my spiritual journey,
for the benefit of those that travel rightly after.
And I can speak it to the glory of God,
He never moved me to anything but that He gave me power to perform it,
and made it effectual, although I passed through much exercise in the performance of it.
The power of God wrought in me long before I knew what it was;
and when Friends came my understanding was opened,
I soon took up the cross and came into the obedience,
and the Lord cleansed me by his power, and made me a vessel fit for his use.

When I had laboured for a time at home, He called me forth to labour abroad,
and I stood so in the dread, awe, and fear of the Lord,
that his Spirit strove much with me before I could open my mouth;
and the word of the Lord came unto me in a meeting that the Lord
would have war with Amalek from generation to generation;
and the power and Spirit of the Lord was so strong in me, that it set me upon my feet,
and constrained me to speak the words, for I never was hasty nor forward.

Then the Lord caused me to abstain from all flesh, wine, and beer whatsoever,
and I drank only water for the space of a whole year;
and in that time the Lord caused me to grow and to prosper in the Truth;
and then I was made to go and call the people forth from among the dumb idols,
and suffered much imprisonment for it;
but yet I was made to go till the Lord gave me dominion,
so that I could go into their places and say what I had to say,
and come forth again quietly.
As Mary Prince and I were coming arm in arm from
a meeting that was at George Bishop`'s house,
there was a rude man who came and abused us, and struck off Mary Prince`'s hat,
and ran some sharp knife or instrument through all my clothes into my side, which,
if it had gone but a little farther, it might have killed me;
but my soul was so in love with the Truth,
that I could have given up my life for it at that day.

Then I was moved to go to Marlborough, to the market-place and steeple-house,
where I had much service, where they put me in prison for six weeks,
where I fasted six days and six nights, and neither ate bread nor drank water,
nor any earthly thing; then I came to a feeding upon the Word,
and had experience that man does not live by bread alone,
but by every word that proceeds out of the mouth of the Lord.
When I was released I went to Isaac Burges, the man that committed me,
and discoursed with him, and he was really convinced of the Truth,
but could not take up the cross; but was afterwards very loving to Friends,
and stood by them upon all occasions, and never persecuted a Friend anymore;
and when he came unto this city, he came unto my house to see me,
and confessed that he could not take up the cross, although he knew it was the truth.

A while after I was made to go into Devonshire, to Melton, Barnstaple, and Bideford,
where a prison was my lot in all those places; and I went to the Earl of Bath`'s,
where I had formerly spent much time in vanity,
to call unto them to come out of their vanity.

I asked to speak with the countess, and they refused to let me in,
but one of the servants that knew me, bid me go to the back-door,
and their lady would come forth that way to go into the garden.
They sent forth a great wolf-dog upon me, which came fiercely at me to devour me;
but just as he came unto me, the power of the Lord smote the dog, so that he whined,
and ran in crying and very lame,
so that I saw clearly the hand of the Lord in it for my preservation,
blessed be his name; and then the lady came forth,
and stood still and heard me all that I had to say unto her;
and when I had done she gave me thanks, but never asked me to go into her house,
although I had eaten and drank at her table, and lodged there many a time.

Then I was moved to go to Great Torrington in Devonshire, unto the steeple-house there,
where was a very bad priest indeed, though I had not much to say to him,
but to the people; and when I had spoken in the morning, I went to my lodging,
and what I had not room to clear myself of, I put in writing,
and the constables came and took away my writing,
and commanded me to go along with them to their worship;
but I answered them that they would not allow me to speak there,
and that I knew no law that compelled me to go twice in a day,
and they all knew that I was there in the morning, and so I would not go.
The next day the mayor sent for me, and when I came the priest was there,
and the mayor was moderate, and reluctant to send me to prison,
but the priest was very eager and said I ought to be whipped for a vagabond.
I bid him prove where ever I asked anyone for a bit of bread;
but he said I had broken the law by speaking in their church.
So he was so eager with the mayor that he made him make a court order,
and send me to Exeter prison, which was twenty miles distant,
where I remained for some time,
and was commanded of the Lord to fast fourteen days and fourteen nights,
without tasting bread or water, or any earthly thing,
which I performed for a witness against that dark professing people;
and there I was until the court sessions without being brought to a trial;
but after the court sessions were over, a petty fellow sent for me,
and read a law which was quite wrong, and did not relate to me at all,
and put me to lodge one night among a great company
of gipsies that were then in the prison,
and the next day the sheriff came with a beadle, and had me into a room,
and whipped me till the blood ran down my back, and I never started at a blow;
but the Lord made me to rejoice that I was counted worthy to suffer for his name`'s sake,
and I sang aloud.
The beadle said, "`Do you sing?
I shall make you cry by and by,`" and with that he laid more stripes,
and laid them on very hard.

I shall never forget the large experience of the
love and power of God which I had in my travels,
and therefore I can speak to his praise and glorify his name;
for had the beadle whipped me to death in the state I then was,
I should not have been terrified or dismayed at it.
Ann Speed was an eye-witness of it,
and she stood and looked in at the window and wept bitterly.
Then the sheriff, when he saw that the envy of the man could not move me,
bid him forbear, for he had gone beyond his orders already.

When he had left me, Ann Speed came in and dressed my wounds;
and the next day they turned me out with all the gipsies,
and the beadle followed us two miles out of the city, and as soon as he left us,
I returned back again,
and went up into the prison to see my friends that were prisoners there at the same time;
so I took my leave of them and went to Topsham,
where there was a fine meeting of Friends, among whom I was sweetly refreshed,
and stayed there one night, and then I came home to Bristol.
In my travels I went several miles upon long downs, and knew nothing of the way,
but as the Lord was with me, and did direct me;
and in all this I have experience of the love and power of the Lord towards me,
blessed be his name forever.
I cannot forget His lovingkindness to me in my distress.

In my travels near Bridgewater I went to speak to a priest that I had formerly known,
one Edward Piggot; and when I came back to the inn, where I had bespoke my lodging,
they would not let me come in;
so I looked about for shelter to keep me from the fierceness of the frost,
and I found the pig-sty swept very clean and the trough turned up, and no pig in it.
I sat me down on the trough, and that was my lodging all that night,
and the next night I could get no lodging, but was willing to lodge in a barn;
and in all this the Lord exercised me in the patience.

Then I went to Bideford, and there I was put into the town-hall,
and they searched me to see whether I had knife or scissors about me,
and the next day they brought me before the mayor for speaking in a private meeting,
and he discoursed much with me, and had a sense of what I said unto him, and received it;
and at last he set open two doors, one right against the other,
and said he would give me my choice which I would
go forth at--whether I would go to prison again,
or go home.
I told him that I should choose liberty rather than bonds; so I went homeward,
and then he took his horse and came and followed me,
for there was some tenderness in him, and he would have had me ride behind him,
but I found that when anybody whom he knew met us,
then he would draw back and lag behind,
and as soon as they were gone he would come up to me again;
so I would not ride behind him, but he rode three or four miles with me,
and discoursed me all the way;
and when we parted I was made to kneel down and pray for him,
in which time he was very serious, and afterwards grew very solid and sober,
and in a little time he died, but I wrote to him once before he died,
a little after I came home.

And then I was moved of the Lord to go to Basing-stoke,
to endeavour to obtain the liberty of two Friends, namely,
Thomas Robison and Ambrose Rigge,^
footnote:[See The Journal and Writings of Ambrose Rigge, www.friendslibrary.com],
who were taken up at the first meeting that Friends had there,
and when I came they would not let me come in to them.
Having a letter from John Camm unto them, I put it in at a chink of the door to them,
and then I went to the mayor to desire their liberty,
and he told me that if he should see the letter which
I brought them they should have their liberty;
I told him he should, so I went and fetched it to him, and he read it,
and could see no harm in it; so he told me I should have my brethren out,
but he would not let them out presently.
Nevertheless we had a fine meeting the next day, being First-day;
and coming from the meeting I met with the priest, and told him his portion,
and in a few days the Friends had their liberty;
thus the Lord made my journey prosperous.

The Lord moved me to go to Ireland (1656), and I went in a vessel bound for Cork,
and the Lord so ordered it, that the ship was carried about to Dublin,
and we had much foul weather, so that the seamen said that I was the cause of it,
because I was a Quaker; and they conspired to fling me overboard,
but it being made known to me,
I went to the master and told him what his men had designed to do, and told him,
that if he permitted them to do it, my blood would be required at his hands.
So he charged them not to meddle with me;
and afterwards we were in a storm upon a First-day, and I was moved to go upon deck,
and speak among them, and pray for them; and they were all made very quiet, and said,
"`They were more beholden to me than they were to their priest,
because I prayed for them, and he could not open his month to say anything among them.`"
We were six days and six nights at sea, and the master himself did not know where he was,
nor which way he was going, until we were put into the harbour at Dublin;
and although we had abundance of very stormy weather,
yet we sustained no manner of loss nor damage,
so that the master said he could never say before that he was in so much foul weather,
and received no hurt.
We were put into Dublin the very same day that Francis Howgill^
footnote:[See The Life of Francis Howgill, and Some of the Mysteries of God`'s
Kingdom Declared by Francis Howgill, www.friendslibrary.com]
and Edward Burrough^
footnote:[See The Life of Edward Burrough, www.friendslibrary.com]
were banished from there.

Then I saw my service there, and was moved to go to the deputy.^
footnote:[This was Henry Cromwell, son of Oliver Cromwell,
Lord Protector of the Commonwealth of England.]
When I came there, the people said there was no speaking with him;
for did I not know that he had banished two of our Friends out of the nation but yesterday.
But in the faith I went, and the power of the Lord had great weight upon me,
and I met with the secretary, and desired him to help me to speak with the deputy.
He answered me, "`That he did not think he could.`"
I told him,
if he would be so civil as to go up and tell the deputy
that there was a woman below that would speak with him;
then if he refused I would be satisfied.
So he went up, and there came a man to fetch me up into the drawing room.

After I had been there a while, there came a man out of the deputy`'s chamber,
and they all stood bareheaded before him, because they knew I never saw the deputy;
but I had a sense it was a priest: and there was almost a whole room full of people,
and they asked me, "`Why did not I give my message to their lord?`"
I answered, "`When I do see your lord, then I shall give my message to him.`"
So in a little while he came forth, and sat down on a couch,
and I stood up and spoke to him that which the Lord gave me to speak,
and bid him beware that he was not found fighting against God in opposing the Truth,
and persecuting the innocent, but be like wise Gamaliel, to let it alone,
and if it be of God it will stand; but if it be of man it will fall;
that the enmity did not lie so much in himself,
as he was stirred up to it by evil magistrates and bad priests;
and that God`'s people are as dear to him now as ever,
and they that touched them touched the apple of his eye.
But in his (the deputy`'s) name and by his power there was
much hurt done to the people of God all the nation over,
and it would lie heavy upon him at the last;
and that the teachers of the people caused them to err,
and he knew the priest`'s portion; and when I touched upon that,
he would say to the priest that stood there, "`There`'s for you, Mr. Harrison.`"
And the power and presence of the Lord was so with me,
that it made the man to be much concerned.

And when I had done, he asked the priest what he had to say to that which I spoke.
And the priest said it was all very true and very good,
and he had nothing to say against it, if we spoke as we meant.
Then I told the priest, that the Spirit of God was true, and spoke as it meant,
and meant as it spoke; but men of corrupt minds perverted the Scriptures,
by putting their own imaginations and conceivings, and apprehensions upon them,
and so deceived the people; but holy men of God spoke the Scriptures,
and gave them forth as they were inspired by the Holy Spirit,
and they are of no private interpretation;
but none understood them but those that read them
by the same Spirit that gave them forth.
So I returned to my lodging, which was at one Captain Rich`'s house,
and he came home and said,
"`that the deputy was so sad and melancholy after I had been with him,
that he would not come forth to bowls nor any pastime at all.`"

Thus my service for God was great, and he made it to prosper.
Then I went to Cork, where my motion was at first, and great were my sufferings there,
for a prison was my lot almost wherever I came;
and I was made to call to my relations and acquaintance, by the Word of the Lord,
and to follow them into several steeple-houses.
Great were my sufferings among them, but wherever the Lord opened my mouth,
there were some that received me, and would plead my cause against my persecutors.
I was in jeopardy of my life several times, but the Lord preserved me.
I was made to speak in a market-place,
and there was a butcher swore he would cleave my head in twain;
and had his cleaver up ready to do it, but there came a woman behind him,
and caught back his arms, and stayed them till the soldiers came and rescued me.

Those that were my former acquaintances, with whom I had formerly been very conversant,
and spent much time, and lodged at their houses several times,
even those now were afraid of me, and would not come near me,
but the dread of God was upon me, and it made some of them to tremble.
Some said I was a witch, and when I would go to their houses to reprove them,
they were so mad that they would run away,
and then their servants would come and hale me out; and when I would go to sit down,
they would drag me along upon the stones, and hale me out and shut the doors:
so I came to witness that a prophet is not without honour, save in his own country.
And when I found myself pretty clear there, I returned home to Bristol.

In a while after I was moved to go to Ireland again,
and then I was in great perils by sea, where I saw the wonders of the Lord in the deep.
There was one man Friend and one woman Friend in the ship besides me,
and the ship was broken near Dungarvan, and foundered in the sea,
somewhat near the shore, and we were all likely to be cast away.
I was ordered of the Lord to stay in the ship until they were all gone out of her,
and the master and the passengers got into the boat
(all save one man and one woman who were cast away),
got to shore, and stood there to see what would become of me, who was still in the cabin,
and the waves beat in upon me in abundance, almost ready to stifle me.
When I found freedom I went and stood upon a piece of the deck that was left,
and then the master of the vessel and the man Friend called to me, and told me,
if I would venture to leap down, they would venture to come into the water to save me.
So they came into the water up so far as their necks, and I leaped down to them,
and they caught hold of me, but I being entangled in the ropes in leaping down,
was drawn from them again; but as the Lord ordered it, a wave came and beat the ship out,
whereas, if it had beat in, it would have killed us all three, but beating out,
they recovered me again, and drew me to shore.
So the Lord`'s power and mercy were wonder fully shown at that time for my preservation;
I can not but bless His name for it.

Then I went to Dublin, where I spoke in the high court of justice among the judges,
and then they put me in prison, where I lay upon straw on the ground, and when it rained,
the wet and filth ran in under my back.
They arraigned me at the bar, and bid me plead guilty or not guilty.
I answered,
that there was no guilt upon anyone`'s conscience
for what they did in obedience to the Lord God.
And the judge could not speak to me,
but spoke to another man that stood by him to speak to me.
So I could not say as they bid me, and they returned me to prison again,
where I had very hard exercise.
And there was a man that could not enjoy some land,
except he could prove that his brother was dead;
and he brought a man into prison that said "`he would
prove that he was killed at such an inn,
and buried under a wall.`"
He accused the innkeeper and his wife, and their man and maid, and a smith,
to be guilty of this murder.

So I went to him, and sat down by him, and spoke a few words to him,
and asked him how he could conceal this murder so long,
when he was as guilty of it as either of them, if it were true?
He trembled and shook exceedingly, and his knees smote one against another,
and he confessed "`that he never saw the people with his eyes,
nor never was at the place in his life, nor knew nothing of it,
but only he was drawn in by the man that was to have the laud,
and was persuaded to witness it.`"
The prisoners heard this his confession to me,
so I sent to the deputy to send down his priest, that he might hear his confession;
so he came, and he confessed the same to him as he had done to me;
and the five persons whom he accused were then in prison,
but only the maid in the prison with me,
and the man confessed the same once before the judge.
But the man that brought him in came to him every day, and filled him with drink,
and caused the jailer to lock me up, that I might not come at him.

So I wrote to the innkeeper and his wife and the coachman, and to the judge also,
and told him the day of his death drew nigh,
wherein he must give an account of his actions,
and bid him take heed how he condemned so many innocent people, having but one witness,
in whose mouth there were so many lies found; and they all said they were innocent.
They called him Judge Pepes who condemned them all.

Then a priest came to speak with the maid that was condemned,
who was with me in the prison, but she would not see him, but said, "`No,
he can do me no good; I have done with man forever.
But God, you know that I am innocent of what they lay to my charge.`"
So they were all hanged, and the man that accused them was hanged up first,
for fear he should confess when he saw the rest hanged.
And a heavy day it was, and I bore and suffered much that day.

Then there were some friends of mine, namely--Sir William King, Colonel Fare,
and the Lady Browne, these hearing I was in prison, came to see me,
and they would needs go to this judge, to get me released; so when they came,
he told them that he was afraid for his life.
And they laughed, and told him they had known me from a child,
and there was no harm in me at all.
They were all very earnest to get my liberty, and at last they did obtain it.
Then I was moved to go to the steeple-house where this judge was,
and the Lord was with me, and I cleared myself of him;
and he went to bed and died that night.
One of the prisoners had written the letter which I sent to him,
and when they heard he was dead, they all said that I was a true prophetess unto him.

Thus as an instrument in the hand of the Lord to do his work,
I was faithful and obedient unto his power,
and he caused me so to grow and prosper through my great sufferings, that,
blessed be His name forever, I had great experience of his love and power.
Elizabeth Gardiner and Rebecca Rich, and Samuel Claridge`'s wife knew all this to be true.

I then went to Limerick, where I had some service, and they put me in prison.
So in a while I was released.
Then I took shipping for England again, and there was a great storm took us at sea;
and the Lord moved me to go to prayer; and in a little time the storm ceased,
and we were preserved.
On coming towards Mineyard we met a pirate, which had abundance of men on board,
and I began to consider whether there was any service
for me to do among those rude people,
but I found little to them; so they came on board of us, and took away all that I had,
and one of my coats from off my back;
but they were not permitted to do me any further harm.
They took away the master with them,
until he should pay them a sum of money for the ship and goods.
So we came home to England.
But in all my travels I went on my own purse, and was never chargeable to any,
but paid for what I had.

Much more could I declare of my sufferings which I passed through,
which I forbear to mention, being not willing to be over-tedious.

And I have written these things that Friends may be encouraged, and go on in the faith,
in the work of the Lord; for many have been the trials, tribulations,
and afflictions which I have passed through,
but the Lord has delivered me out of them all.
Glory be given to Him, and blessed be His name forever and evermore.

[.signed-section-signature]
Barbara Blaugdone.
