== A Short Account of Barbara Blaugdone

In my youth and tender years I feared the Lord, and was afraid to offend Him,
being zealous and diligent in the religious profession of my upbringing.
I sought the Lord earnestly, although I knew not where to find Him,
until I was directed by two Friends, John Audland and John Camm,^
footnote:[See "`A Testimony to the glorious morning
of the day of visitation of the love of God,
and to the great and mighty power of the Lord,
which appeared in and with his two precious servants John Camm and John Audland,
who came to that city in the year 1654,`" in the
fourth chapter of Charles Marhsall`'s journal, www.friendslibrary.com.]
who came down from the north of England in the year 1654.
Their behavior and deportment was such that it preached
to me before they ever opened their mouths,
and it was then revealed to me that they had the
everlasting gospel to preach in this city.
When they did open their mouths,
I was made to bless God that I had lived to hear the preaching of the everlasting gospel;
for they directed our minds unto the light of Christ, and told us to wait therein,
which I was diligent to do, and in time came to find the virtue of it.
And as any evil was made manifest in me, I departed from it,
and willingly took up the cross, and yielded obedience to it even in little things,
such as plainness of speech and apparel.
And when I went into their public places and steeple-houses to speak the truth,
the people were so offended that they took away their children from my school,
so that I lost almost all my employment,
and they often kept me in prison for up to a quarter of a year at a time.
Great were my sufferings in that day,
but the Lord so filled me with His power that I was preserved through it all;
for the diligent and faithful ones prospered then, as they do now.

Therefore my counsel to Friends is that they keep in God`'s power;
for there is no other way to be preserved nor to receive
life and salvation--this is my testimony for God.
For whoever shuns the cross goes out from the power,
and will lose their way and dishonor God.
But whoever keeps in the faith and abides in the power remains in safety.
I have had living experience of this,
and it has been with me a long while to publish it
for the benefit of those that are now passing through,
or are yet to pass through sufferings.
For this reason I declare my experience.

And so, dear Friends, the cross is the way to the crown of life and glory;
and those who continue faithful and obedient will obtain the eternal crown,
while those who are disobedient will lose it.
I speak my experience of the dealings of the Lord with me in my spiritual journey,
for the benefit of those that rightly travel on after me.
And I can speak it to the glory of God,
that He never moved me to do anything without also giving me the power to perform it,
and also making it effectual,
though I often passed through many trials in the performance of it.
Truly, the power of God wrought in me long before I knew what it was,
but when Friends came and preached the everlasting gospel my understanding was opened.
So I took up the cross and came into true obedience,
and found that the Lord cleansed me by His power, and made me a vessel fit for His use.

When I had labored in the work of the gospel for a time at home,
He called me forth to go labor abroad.
I stood in so much dread, awe, and fear of the Lord,
that His Spirit had to strive much with me before I could open my mouth.
But the word of the Lord came unto me in a meeting,
that "`the Lord would have war with Amalek from generation to generation;`"
and the power and Spirit of the Lord was so strong in me,
that He set me upon my feet and constrained me to speak these words to the people;
for I was never hasty or forward to speak in the Lord`'s name.

Then the Lord caused me to abstain from all meat, wine, and beer,
and I drank only water for the space of a whole year.
But in that time the Lord caused me to grow and to prosper in the Truth.
He then sent me to call people away from their dumb idols,
and I suffered much imprisonment for it.
But I was continually made to go, and the Lord gave me dominion over all opposition,
so that I could go to all and say what I had to say, and then come back quietly again.
And once,
as Mary Prince and I were coming arm in arm from
a meeting that was at George Bishop`'s house,
there was a rude man who came and abused us.
He struck off Mary Prince`'s hat,
and then ran a sharp knife or instrument through all my clothes into my side, which,
if it had gone but a little deeper, would have killed me;
but my soul was so in love with the Truth,
that I could have gladly given up my life for it that day.

Then I was moved to go to Marlborough, to the market-place and steeple-house there,
where I had much service.
For this I was put in prison for six weeks, where I fasted six days and six nights,
and neither ate bread nor drank water, nor any earthly thing;
but I came to know a feeding upon the Word,
and experienced that man does not live by bread alone,
but by every word that proceeds out of the mouth of the Lord.
When I was released I went to see Isaac Burges, the man who had committed me to prison,
and discoursed with him, and he was convinced of the Truth,
but would not take up the cross.
Nevertheless, he was afterwards very loving to Friends,
and stood by them upon all occasions, and never persecuted a Friend again.
And when he came to the city of Bristol, he came to my house to see me,
and confessed that he could not take up the cross, although he knew it was the true way.

A while after this I was moved to go into Devonshire, to Melton, Barnstaple,
and Bideford, where a prison was my lot in all of these places.
I then went to the home of the Earl of Bath, to call them out of vanity,
for in my younger years I had spent much time there in vanity.
I asked to speak with the countess, and they refused to let me in,
but one of the servants who knew me bid me go to the back-door,
saying the lady of the house would come out that way and would go with me into the garden.
But instead of this,
they sent forth their great wolf-dog which ran fiercely towards me to devour me;
but just as he came upon me, the power of the Lord smote the dog,
so that he suddenly whined, and ran away crying and very lame,
and I clearly saw that the hand of the Lord was in it for my preservation,
blessed be His name.
Then the lady of the house came forth,
and stood still and heard all that I had to say to her;
and when I had done she thanked me, but never invited me into her house,
although I had eaten and drank at her table and lodged there many times.

Then I was moved to go to Great Torrington in Devonshire, unto the steeple-house there.
In this place there was a very bad priest indeed,
though I was not given much to say to him, but rather to the people.
And when I had finished speaking in the morning, I went away to my lodging,
and some things that I had not had time to declare
in the steeple-house I then put into writing.
But the constables came to my room and took away my writing,
and commanded me to go along with them to their worship, seeking to ensnare me.
I answered them that they would not allow me to speak there,
and that I knew no law that compelled me to go twice in a day,
and they all knew that I had been there in the morning, so I would not go.
The next day the mayor sent for me, and when I came to him the priest was there.
The mayor was moderate, and reluctant to send me to prison,
but the priest was very eager and said I ought to be whipped as a vagabond.
I bid him to prove that I had ever asked anyone for even a morsel of bread,
but he said I had broken the law by speaking in their church.
He was so unrelenting with the mayor that the mayor at last
made a court order and sent me to Exeter prison,
which was twenty miles distant, where I remained for some time.
There I was commanded of the Lord to fast fourteen days and fourteen nights,
without tasting bread or water, or any earthly thing,
which I performed as a witness against that dark professing people;
and there I remained until the next court sessions
without ever being brought to a trial.

After the court sessions had finished,
a petty constable sent for me and read a law which did not relate to my case at all,
and then made me to lodge one night among a great
company of gypsies that were then in the prison.
The next day the sheriff came with a parish officer,
and brought me into a room where he whipped me till the blood ran down my back,
though I never flinched at a blow.
The Lord made me rejoice that I was counted worthy to suffer for His name`'s sake,
and as he whipped me I sang aloud.
The officer said, "`Do you sing?
I shall soon make you cry!`"
And with that he laid on more stripes, and laid them on very hard.
Truly,
I shall never forget the great experience of the
love and power of God which I had in that day,
and therefore I can speak to His praise and glorify His name;
for had the parish officer whipped me to death in the state I was then in,
I would not have been afraid or dismayed at it.
Ann Speed was an eye-witness of their cruelty,
for she stood and looked in at the window and wept bitterly.
And when the sheriff saw that the malice of the man could not move me, he bid him desist,
for he had gone beyond his orders already in the number of stripes laid upon me.

When he had left me, Ann Speed came in and dressed my wounds;
and the next day they cast me out with all the gypsies,
and the officer forced us two miles out of the city.
But as soon as he left us, I returned back again,
and went back into the prison to visit my friends
who were prisoners there at the same time.
After I took my leave of them I went to Topsham,
where there was a fine meeting of Friends, among whom I was sweetly refreshed,
and I stayed there one night before coming home to Bristol.
In my travels I often went many miles upon large open plains,
and knew nothing of the way, except as the Lord, who was with me, did direct me.
And in all of this I have had great experience of
the love and power of the Lord towards me,
blessed be His name forever.
I cannot forget His lovingkindness to me in my distress.

In my travels near Bridgewater I went to speak with a priest who I had formerly known,
one Edward Piggot; and when I came back to the inn, where I had paid for my lodging,
they would not let me in.
So I looked around for shelter in order to protect me from the fierceness of the frost,
and I found that the pig-sty was swept very clean and the trough was turned up,
with no pig in it.
So I sat down on the trough, and that was my lodging all that night.
Nor could I obtain lodging the following night, but was made willing to lodge in a barn;
and in all these things the Lord exercised me in patience.

Then I went to Bideford, where I was put into the town-hall,
and they searched me to see whether I had a knife or scissors on me.
The next day they brought me before the mayor for
speaking in a private meeting among Friends,
and he discoursed much with me,
and an understanding was given him concerning what I said, and he received it.
At last he set open two doors, one right against the other,
and said he would leave it to me which I would choose--whether
I would go to prison again,
or go home.
I told him that I would rather choose liberty than bonds; so I went homeward.
The mayor then took his horse and followed me, for there was some tenderness in him,
and he requested me to ride behind him.
But I found that when anybody whom he knew met us on the road,
he would then draw back and lag behind me,
and as soon as they were gone he would come up to me again.
Thus he rode three or four miles with me, and discoursed with me all the way;
and when we parted I was moved to kneel down and pray for him,
at which time he was very serious.
After this time he grew very solid and sober, and in a little time after he died.
But I wrote to him once before he died, a short time after I came home.

I was then moved of the Lord to go to Basingstoke,
and to endeavor to obtain the liberty of two Friends, namely,
Thomas Robison and Ambrose Rigge^
footnote:[See The Journal and Writings of Ambrose Rigge, www.friendslibrary.com],
who were taken prisoners at the first meeting of Friends in that place.
But when I came they would not let me see them.
Having a letter from John Camm for them, I passed it to them through a crack in the door,
and then went to the mayor to request their liberty.
He told me that if he could see the letter which
I brought to them they would have their liberty.
I told him he could, so I went and fetched it for him.
When he had read it, and could see no harm in it,
he told me I should have my brethren out, but he would not let them out immediately.
Nevertheless we had a fine meeting the next day, being the first day of the week,
and coming away from the meeting I met with the priest of that place,
and spoke to him what the Lord laid on my heart.
In a few days the Friends had their liberty; thus the Lord made my journey prosperous.

In the year 1656, I was moved to go to Ireland, and I went in a vessel bound for Cork.
But the Lord so ordered it that we had much foul
weather and the ship was carried about to Dublin.
The seamen, seeing the storm, said that I was the cause of it because I was a Quaker,
and they conspired to throw me overboard.
But their plot being made known to me,
I went to the master of the ship and told him what his men designed to do,
and that if he permitted them to do it, my blood would be required at his hands.
So he charged the crew not to meddle with me.
After this we were in a great storm upon a First-day,
and I was moved of the Lord to go upon the deck and
speak to the sailors and pray for them,
and they were all made very quiet,
and said they were more indebted to me than they were to their own priest,
because I had prayed for them,
and he could not open his month or say anything to them at that time.
We were six days and six nights at sea, and the master himself did not know where he was,
nor which direction he was going, until we found ourselves in the harbor at Dublin.
And although we had an abundance of very stormy weather,
yet we sustained no manner of loss or damage,
so that the master said he was never before in such foul weather without receiving hurt.
We put into Dublin the very same day that Francis Howgill^
footnote:[See The Life of Francis Howgill, and Some of the Mysteries of God`'s
Kingdom Declared by Francis Howgill, www.friendslibrary.com]
and Edward Burrough^
footnote:[See The Life of Edward Burrough, www.friendslibrary.com]
were banished from Ireland.

I then saw what my service was there,
and was moved of the Lord to go to the lord deputy of Ireland.^
footnote:[This was Henry Cromwell, son of Oliver Cromwell,
Lord Protector of the Commonwealth of England.]
When I went to him, the people said to me, "`There is no way to speak with him;
do you not know that he banished two of your Friends out of the nation but yesterday?`"
But in faith I went, and the power of the Lord was upon me with great weight.
I met with the secretary, and requested him to help me to speak with the deputy.
He answered me that he did not think he could help me.
I told him,
"`If you would be so civil as to go up and tell the deputy that
there was a woman below that desired to speak with him;
then if he refused, I would be satisfied.`"
So he went up, and soon a man came down to bring me up into another room.

After I had been there a while, a man came out of the deputy`'s chamber,
and many others crowded around and stood before him with their hats off.
They knew that I had never before seen the deputy,
but a sense was given to me that this was not him, but rather a priest.
When the room was nearly full of people, they asked me,
"`Why do you not give your message to our lord the deputy?`"
I answered, "`When I see the deputy, then I shall give my message to him.`"
So after a while the real deputy came forth, and sat down on a couch.
I stood up and spoke to him all that the Lord laid upon me,
and bid him beware that he was not found fighting against God in opposing the Truth,
and persecuting the innocent, but to be like wise Gamaliel, and let it alone,
for if it is of God it will stand; but if it is of man it will fall.
I told him I was aware that the enmity did not lie so much in himself,
but rather that he was stirred up to it by evil magistrates and bad priests;
but that God`'s people were as dear to Him now as ever,
and whoever touched them touched the apple of his eye.
"`But,`" I said to him,
"`in your name and by your power there is much hurt
done to the people of God all the nation over,
and it will lie heavy upon you in the end.`"
Then I told him that the teachers of the people caused them to err,
and that he knew what would be the portion of such priests.
And whenever I touched upon this subject, he would say to the priest that stood there,
"`That is for you, Mr. Harrison.`"
The power and presence of the Lord was so strong with me,
that it caused the deputy to be much concerned.

When I had finished speaking, he asked the priest what he had to say concerning my words.
The priest responded that it was all very true and good,
and he had nothing to say against it, if I meant what I spoke.
Then I told the priest, that the Spirit of God is true, and alway means what He speaks,
and speaks what He means;
but men of corrupt minds pervert the Scriptures by putting their own imaginations,
conceivings, and apprehensions upon them, and so deceive the people.
But holy men of God gave forth the Scriptures as they were inspired by the Holy Spirit.
They are of no private interpretation,
and are only understood when read in the same Spirit that gave them forth.
I then returned to my lodging, which was at one captain Rich`'s house.
And when this captain returned home,
he told me that the lord deputy was so sad and melancholy after I had been with him,
that he would not come out to play at lawn bowling, nor any pastime at all.

Thus my service for God was considerable, and He caused it to prosper.
From there I went to Cork, where I had first felt moved to go,
and great were my sufferings, for a prison was my lot almost everywhere I went.
There I was moved to call upon my relations and acquaintances with the Word of the Lord,
and to follow them into several steeple-houses, and many were my sufferings among them.
But wherever the Lord opened my mouth, there were some who received me,
and these would plead my cause against my persecutors.
My life was in jeopardy several times, but the Lord preserved me.
Once I was moved to speak in a market-place where there
was a butcher who swore he would cleave my head in two,
and he had a meat cleaver raised in order to do it.
But a woman came up behind him, caught his arms,
and held them until the soldiers came and rescued me.

Those who were my former acquaintances,
and with whom I had formerly been very conversant and spent much time,
and lodged at their houses several times, were now afraid of me,
and would not come near me; for the dread of the Lord was with me,
and it made some of them to tremble.
Some said I was a witch, and when I would go to their houses to reprove them for evil,
they were so mad that they would run away,
and then their servants would come and haul me out.
And sometimes, when I would sit down, they would drag me along upon the ground,
throw me out and shut the doors.
So I came to witness the truth of Christ`'s words, that "`a prophet is not without honor,
except in his own country.`"
And when I found my conscience pretty clear of my service there,
I returned home to Bristol.

A while after this I was moved again to go to Ireland,
and along the way I was in great perils by sea,
and saw "`the wonders of the Lord in the deep.`"^
footnote:[Ps. 107:24]
There was one man Friend and one woman Friend in the ship besides me,
and the ship broke apart near Dungarvan,
and began to sink into the sea somewhat near the shore,
and for a time it was thought that all would be lost.
I was ordered by the Lord to stay in the ship until all had gone out of her.
The master of the ship and the passengers managed to get into the row-boat
(all except one man and one woman who were drowned) and then got to shore,
where they watched to see what would become of me; for I was still in the cabin,
and the waves beat in upon me in such abundance that I was almost drowned.
When I felt freedom in the Lord,
I went and stood upon a broken piece of the deck that was left,
and then the master of the vessel and the man Friend
called to me and told me that if I would leap down,
they would venture into the water to save me.
So they came into the water up to their necks, and I leaped down to them,
and they caught hold of me.
But having become entangled in the ropes while leaping down,
I was drawn away from them again.
But as the Lord so ordered it,
just at that moment a wave came and beat the ship away from shore; whereas,
if it had beat the ship towards shore, it would have crushed all three of us.
But as the wind beat the ship outwards, they laid hold of me again, and drew me to shore.
So the Lord`'s power and mercy were wonderfully shown at that time for my preservation,
and I cannot but bless His name for it.

From there I went to Dublin, where I spoke in the High Court of Justice among the judges,
for which I was put into prison.
There I lay upon straw on the ground, and when it rained,
the moisture and excrement from the jail ran in under my back.
After some time they arraigned me at the bar, and told me to plead guilty or not guilty.
Seeing a snare in their words,
I answered that there was no guilt upon anyone`'s conscience
for what they did in obedience to the Lord God.
The judge could not speak directly to me,
and so bid another man that stood by him to speak to me.
But as I did not respond in the manner that they bid me,
they returned me to prison again, where I met with very hard exercises.

There was at that time a rich man in Dublin that could not take possession
of a certain land unless he could prove that his brother was dead;
and he brought a man into the prison who said he would prove
that the rich man`'s brother was murdered at a certain inn,
and buried under a wall.
The man alleged that the keeper of the inn and his wife, together with a servant, a maid,
and a blacksmith, were guilty of this murder.
So I went to this man, sat down by him, and spoke a few words to him.
I asked him how he could conceal this murder so long, if it were indeed true;
for by doing so he had made himself as guilty of it as any of them.
He trembled and shook exceedingly when I spoke to him,
and his knees knocked one against another.
He then confessed freely that he had never seen these people before in his life,
nor had ever been at the inn, and knew nothing of the case,
but had been enticed and persuaded to witness against
them by the rich man who desired to have the land.
The other prisoners heard his confession to me,
so I sent to the deputy and asked him to send for his priest,
that he might come and hear the confession as well.
When the priest came, the man confessed to him as he had done to me,
and also confessed the same privately before Judge Pepes.
The five persons whom he had accused of murder were in the prison,
but only the maid was with me at that time, and heard the man`'s confession.
But the rich man who had brought him came to him every day, spoke to him frequently,
and filled him with strong drink.
He also caused the jailer to lock me up elsewhere,
that I might not come near the man who had confessed.

I therefore wrote of these things to the innkeeper, his wife and their servant.
I wrote also to Judge Pepes, and told him that I saw the day of his death drawing near,
wherein he must give an account of his actions,
and I bid him take heed how he condemned so many innocent people,
having but one witness in whose mouth were so many lies.
But though all five persons declared their innocence,
Judge Pepes condemned them all to death.

The priest then came to speak with the maid who was condemned to be hanged,
and who was with me in the prison, but she refused to see him, saying, "`No,
he can do me no good.
I am done with man forever.
But God, You know that I am innocent of what they lay to my charge.`"
So they were all hanged, and the man that accused them was hanged first,
for fear that he should confess to the truth after seeing the rest hanged.
And truly, a heavy day it was, and I bore and suffered much that day.

There were then some friends of mine, namely, Sir William King, Colonel Fare,
and the Lady Browne, who, upon hearing I was in prison, came to see me.
They said they would go right away and speak with Judge Pepes to get me released.
But when they came to him, he told them that he feared me, and was afraid for his life.
They laughed, and told him they had known me from a child,
and there was no harm in me at all.
They were all very earnest to get my liberty, and at last they did obtain it.
Upon my release I was moved to go to the steeple-house where this judge was,
and the Lord was with me.
I delivered to him all that the Lord laid upon me;
and he then went home to bed and died that night.
One of the prisoners had read the letter which I had sent to him,
and when they heard that he was dead,
they said that I had been a true prophetess unto him.

Thus as an instrument in the hand of the Lord to do His work,
I was faithful and obedient unto His power,
and He caused me so to grow and prosper through my great sufferings, that,
blessed be His name forever, I had great experience of both His love and His power.
Elizabeth Gardiner, Rebecca Rich, and Samuel Claridge`'s wife know all of this to be true.

From there I went to Limerick, where I had some service, and was put into prison again.
But after a while I was released, and I then took shipping for England.
There was again a great storm that overtook us at sea, and the Lord moved me to pray,
and in a little time the storm ceased and we were preserved.
On coming towards Mineyard we met with a pirate ship
that had an abundance of men on board,
and I began to consider whether there might be some
service for me to do among those rude people,
but I found little towards them.
They came on board our ship and took away all that I had,
and one of my coats from off my back,
but they were not permitted to do me any further harm.
They took away the master of our vessel with them,
until he should pay them a sum of money for the ship and goods,
but we at last came home to England.
In all my travels I went on my own purse, and was never chargeable to any,
but paid for all of my necessities.

Much more could I declare of the sufferings that I passed through, but I forbear,
being unwilling to be tedious.
And I have written these things for the sole purpose that Friends may be encouraged,
and go on in the faith and the work of the Lord.
For many have been the trials, tribulations, and afflictions that I have passed through,
but the Lord has delivered me out of them all.
May glory be given to Him, and may His name be blessed forever and evermore.

[.signed-section-signature]
Barbara Blaugdone
